import type { BookTheme } from '../types.ts'
import { DEFAULT_PARAGRAPH_SPACING_EM } from './paragraph.ts'

const defaults: Omit<BookTheme, 'id' | 'name'> = {
  preset: true,
  favorite: false,
  chapterHeading: {
    showNumber: true,
    showTitle: true,
    showSubtitle: true,
    numberView: 'arabic',
    titleFont: 'Libre Baskerville',
    titleSize: 28,
    titleAlign: 'center',
    titleWeight: 'bold',
    subtitleFont: 'Libre Baskerville',
    subtitleSize: 14,
    numberFont: 'Libre Baskerville',
    numberSize: 14,
    imageEnabled: true,
    imagePlacement: 'above',
    imageSize: 56,
    imageAlign: 'center',
    useIndividualImages: false,
    backgroundOpacity: 0.35,
    lightText: false,
    decorations: [],
  },
  paragraph: {
    dropCaps: true,
    leadInSmallCaps: false,
    firstSentenceMode: 'chapter',
    paragraphStyle: 'indent',
    paragraphSpacingEm: DEFAULT_PARAGRAPH_SPACING_EM,
    bodyAlign: 'justify',
  },
  subheading: {
    h2Size: 1.2,
    h3Size: 1.15,
    h4Size: 1.12,
    h5Size: 1.09,
    h6Size: 1.07,
    font: 'Libre Baskerville',
    weight: 'bold',
    align: 'left',
  },
  sceneBreak: {
    style: 'ornament',
    ornament: '⁂',
    size: 18,
  },
  specialBlocks: {
    verseIndentEm: 1.5,
    verseLineSpacing: 1.25,
    hangingIndentEm: 1.5,
    quoteIndentEm: 1.25,
    quoteBorderWidth: 2,
    quoteItalic: true,
  },
  notes: {
    epubPlacement: 'chapter-end',
    printPlacement: 'footnotes',
    fontSize: 11,
  },
  print: {
    trimWidthIn: 6,
    trimHeightIn: 9,
    marginInside: 0.75,
    marginOutside: 0.5,
    marginTop: 0.6,
    marginBottom: 0.6,
    justified: true,
    hyphens: true,
    keepSubheadings: true,
    keepSceneBreaks: true,
    layoutPriority: 'best-of-both',
    largePrint: false,
  },
  typography: {
    bodyFont: 'Palatino Linotype',
    bodySize: 11,
    lineSpacing: 1.4,
  },
  headerFooter: {
    layout: 'chapter-page',
    font: 'Libre Baskerville',
    size: 9,
  },
}

function baseTheme(
  partial: Partial<BookTheme> & Pick<BookTheme, 'id' | 'name'>,
): BookTheme {
  return {
    ...defaults,
    ...partial,
    chapterHeading: { ...defaults.chapterHeading, ...partial.chapterHeading },
    paragraph: { ...defaults.paragraph, ...partial.paragraph },
    subheading: { ...defaults.subheading, ...partial.subheading },
    sceneBreak: { ...defaults.sceneBreak, ...partial.sceneBreak },
    specialBlocks: { ...defaults.specialBlocks, ...partial.specialBlocks },
    notes: { ...defaults.notes, ...partial.notes },
    print: { ...defaults.print, ...partial.print },
    typography: { ...defaults.typography, ...partial.typography },
    headerFooter: { ...defaults.headerFooter, ...partial.headerFooter },
  }
}

export const PRESET_THEMES: BookTheme[] = [
  baseTheme({ id: 'theme-classic', name: 'Classic', favorite: true }),
  baseTheme({
    id: 'theme-modern',
    name: 'Modern',
    chapterHeading: {
      ...defaults.chapterHeading,
      showSubtitle: false,
      titleFont: 'Source Sans 3',
      titleSize: 30,
      titleAlign: 'left',
      subtitleFont: 'Source Sans 3',
      numberFont: 'Source Sans 3',
      imageEnabled: false,
      imageAlign: 'left',
    },
    typography: { bodyFont: 'Georgia', bodySize: 11, lineSpacing: 1.45 },
    sceneBreak: { style: 'space', ornament: '', size: 16 },
    paragraph: {
      ...defaults.paragraph,
      dropCaps: false,
      leadInSmallCaps: true,
      firstSentenceMode: 'chapter',
      paragraphStyle: 'space',
      bodyAlign: 'left',
    },
  }),
  baseTheme({
    id: 'theme-romance',
    name: 'Romance',
    chapterHeading: {
      ...defaults.chapterHeading,
      showNumber: false,
      numberView: 'none',
      titleSize: 32,
      titleWeight: 'normal',
      imageSize: 48,
    },
    sceneBreak: { style: 'ornament', ornament: '❀', size: 16 },
    typography: { bodyFont: 'Garamond', bodySize: 11.5, lineSpacing: 1.5 },
  }),
  baseTheme({
    id: 'theme-mystery',
    name: 'Mystery',
    chapterHeading: {
      ...defaults.chapterHeading,
      showSubtitle: false,
      numberView: 'words',
      titleFont: 'Georgia',
      titleSize: 26,
      subtitleFont: 'Georgia',
      numberFont: 'Georgia',
      imageEnabled: false,
    },
    sceneBreak: { style: 'ornament', ornament: '◆', size: 14 },
    typography: { bodyFont: 'Times New Roman', bodySize: 11, lineSpacing: 1.35 },
  }),
  baseTheme({
    id: 'theme-fantasy',
    name: 'Fantasy',
    chapterHeading: {
      ...defaults.chapterHeading,
      numberView: 'roman',
      titleSize: 30,
      imageSize: 64,
    },
    sceneBreak: { style: 'ornament', ornament: '❖', size: 18 },
  }),
  baseTheme({
    id: 'theme-scifi',
    name: 'Sci‑Fi',
    chapterHeading: {
      ...defaults.chapterHeading,
      showSubtitle: false,
      titleFont: 'Source Sans 3',
      titleAlign: 'left',
      subtitleFont: 'Source Sans 3',
      numberFont: 'Source Sans 3',
      imageEnabled: false,
      imageAlign: 'left',
    },
    sceneBreak: { style: 'ornament', ornament: '◇', size: 14 },
    typography: { bodyFont: 'Georgia', bodySize: 11, lineSpacing: 1.4 },
    paragraph: {
      ...defaults.paragraph,
      dropCaps: false,
      leadInSmallCaps: false,
      firstSentenceMode: 'chapter',
      paragraphStyle: 'space',
      bodyAlign: 'left',
    },
  }),
  baseTheme({
    id: 'theme-thriller',
    name: 'Thriller',
    chapterHeading: {
      ...defaults.chapterHeading,
      showSubtitle: false,
      titleFont: 'Georgia',
      titleSize: 24,
      titleAlign: 'left',
      subtitleFont: 'Georgia',
      numberFont: 'Georgia',
      imageEnabled: false,
      imageAlign: 'left',
    },
    sceneBreak: { style: 'ornament', ornament: '—', size: 16 },
    typography: { bodyFont: 'Times New Roman', bodySize: 11, lineSpacing: 1.35 },
  }),
  baseTheme({
    id: 'theme-literary',
    name: 'Literary',
    chapterHeading: {
      ...defaults.chapterHeading,
      showNumber: false,
      showSubtitle: false,
      numberView: 'none',
      titleSize: 26,
      titleWeight: 'normal',
      imageEnabled: false,
    },
    sceneBreak: { style: 'ornament', ornament: '* * *', size: 14 },
    typography: { bodyFont: 'Garamond', bodySize: 11.5, lineSpacing: 1.5 },
  }),
  baseTheme({
    id: 'theme-nonfiction',
    name: 'Nonfiction',
    chapterHeading: {
      ...defaults.chapterHeading,
      titleFont: 'Source Sans 3',
      titleSize: 26,
      titleAlign: 'left',
      subtitleFont: 'Source Sans 3',
      numberFont: 'Source Sans 3',
      imageEnabled: false,
      imageAlign: 'left',
    },
    paragraph: {
      ...defaults.paragraph,
      dropCaps: false,
      leadInSmallCaps: false,
      firstSentenceMode: 'chapter',
      paragraphStyle: 'space',
      bodyAlign: 'left',
    },
    typography: { bodyFont: 'Georgia', bodySize: 11, lineSpacing: 1.45 },
    sceneBreak: { style: 'space', ornament: '', size: 14 },
    notes: { epubPlacement: 'book-end', printPlacement: 'footnotes', fontSize: 10 },
  }),
  baseTheme({
    id: 'theme-memoir',
    name: 'Memoir',
    typography: { bodyFont: 'Palatino Linotype', bodySize: 11.5, lineSpacing: 1.5 },
    sceneBreak: { style: 'ornament', ornament: '· · ·', size: 16 },
  }),
  baseTheme({
    id: 'theme-ya',
    name: 'Young Adult',
    chapterHeading: {
      ...defaults.chapterHeading,
      showSubtitle: false,
      titleFont: 'Source Sans 3',
      subtitleFont: 'Source Sans 3',
      numberFont: 'Source Sans 3',
      imageSize: 52,
    },
    typography: { bodyFont: 'Georgia', bodySize: 11.5, lineSpacing: 1.5 },
  }),
  baseTheme({
    id: 'theme-childrens',
    name: "Children's",
    chapterHeading: {
      ...defaults.chapterHeading,
      showNumber: false,
      showSubtitle: false,
      numberView: 'none',
      titleFont: 'Source Sans 3',
      titleSize: 30,
      subtitleFont: 'Source Sans 3',
      numberFont: 'Source Sans 3',
      imageSize: 72,
      useIndividualImages: true,
      backgroundOpacity: 0.2,
    },
    paragraph: {
      ...defaults.paragraph,
      dropCaps: false,
      leadInSmallCaps: false,
      firstSentenceMode: 'chapter',
      paragraphStyle: 'space',
      bodyAlign: 'left',
    },
    typography: { bodyFont: 'Georgia', bodySize: 14, lineSpacing: 1.6 },
    print: {
      ...defaults.print,
      trimWidthIn: 8.5,
      trimHeightIn: 8.5,
      marginInside: 0.6,
      marginOutside: 0.6,
      marginTop: 0.5,
      marginBottom: 0.5,
      justified: false,
      hyphens: false,
      layoutPriority: 'balanced',
    },
  }),
  baseTheme({
    id: 'theme-poetry',
    name: 'Poetry',
    chapterHeading: {
      ...defaults.chapterHeading,
      showNumber: false,
      showSubtitle: false,
      numberView: 'none',
      titleSize: 22,
      titleWeight: 'normal',
      imageEnabled: false,
    },
    paragraph: {
      ...defaults.paragraph,
      dropCaps: false,
      leadInSmallCaps: false,
      firstSentenceMode: 'chapter',
      paragraphStyle: 'space',
      bodyAlign: 'left',
    },
    typography: { bodyFont: 'Garamond', bodySize: 12, lineSpacing: 1.7 },
    print: {
      ...defaults.print,
      trimWidthIn: 5.5,
      trimHeightIn: 8.5,
      marginInside: 0.7,
      marginOutside: 0.6,
      marginTop: 0.7,
      marginBottom: 0.7,
      justified: false,
      hyphens: false,
      layoutPriority: 'widows-orphans',
    },
  }),
  baseTheme({
    id: 'theme-academic',
    name: 'Academic',
    chapterHeading: {
      ...defaults.chapterHeading,
      titleFont: 'Times New Roman',
      titleSize: 24,
      titleAlign: 'left',
      subtitleFont: 'Times New Roman',
      numberFont: 'Times New Roman',
      imageEnabled: false,
      imageAlign: 'left',
    },
    paragraph: {
      ...defaults.paragraph,
      dropCaps: false,
      leadInSmallCaps: false,
      firstSentenceMode: 'chapter',
      paragraphStyle: 'indent',
      bodyAlign: 'justify',
    },
    typography: { bodyFont: 'Times New Roman', bodySize: 12, lineSpacing: 2 },
    notes: { epubPlacement: 'book-end', printPlacement: 'footnotes', fontSize: 10 },
  }),
  baseTheme({
    id: 'theme-large-print',
    name: 'Large Print',
    print: {
      ...defaults.print,
      marginOutside: 0.6,
      marginTop: 0.7,
      marginBottom: 0.7,
      hyphens: false,
      layoutPriority: 'widows-orphans',
      largePrint: true,
    },
    typography: { bodyFont: 'Georgia', bodySize: 16, lineSpacing: 1.6 },
    paragraph: {
      ...defaults.paragraph,
      dropCaps: false,
      leadInSmallCaps: false,
      firstSentenceMode: 'chapter',
      paragraphStyle: 'space',
      bodyAlign: 'left',
    },
  }),
  baseTheme({
    id: 'theme-minimal',
    name: 'Minimal',
    chapterHeading: {
      ...defaults.chapterHeading,
      showSubtitle: false,
      titleFont: 'Source Sans 3',
      titleSize: 22,
      titleWeight: 'normal',
      subtitleFont: 'Source Sans 3',
      numberFont: 'Source Sans 3',
      imageEnabled: false,
    },
    sceneBreak: { style: 'space', ornament: '', size: 12 },
    paragraph: {
      ...defaults.paragraph,
      dropCaps: false,
      leadInSmallCaps: false,
      firstSentenceMode: 'chapter',
      paragraphStyle: 'space',
      bodyAlign: 'left',
    },
    typography: { bodyFont: 'Georgia', bodySize: 11, lineSpacing: 1.4 },
    headerFooter: { layout: 'page-center', font: 'Source Sans 3', size: 9 },
  }),
  baseTheme({
    id: 'theme-boston',
    name: 'Boston Terrier',
    favorite: true,
    chapterHeading: {
      ...defaults.chapterHeading,
      showNumber: false,
      numberView: 'none',
      subtitleSize: 13,
    },
    paragraph: {
      ...defaults.paragraph,
      dropCaps: true,
      leadInSmallCaps: false,
      firstSentenceMode: 'chapter-and-scene',
      paragraphStyle: 'indent',
      bodyAlign: 'justify',
    },
    sceneBreak: { style: 'ornament', ornament: '🐾', size: 16 },
    typography: { bodyFont: 'Palatino Linotype', bodySize: 11, lineSpacing: 1.45 },
  }),
]

export function cloneTheme(theme: BookTheme, name: string): BookTheme {
  return {
    ...structuredClone(baseTheme(theme)),
    id: `theme-${crypto.randomUUID()}`,
    name,
    preset: false,
    favorite: false,
  }
}

export function getThemeById(themes: BookTheme[], id: string): BookTheme {
  const found = themes.find((t) => t.id === id) ?? themes[0] ?? PRESET_THEMES[0]
  return baseTheme(found)
}

export const TRIM_SIZES = [
  { label: '5 × 8"', width: 5, height: 8, kdp: true, ingram: true },
  { label: '5.25 × 8"', width: 5.25, height: 8, kdp: true, ingram: true },
  { label: '5.5 × 8.5"', width: 5.5, height: 8.5, kdp: true, ingram: true },
  { label: '6 × 9"', width: 6, height: 9, kdp: true, ingram: true },
  { label: '6.14 × 9.21"', width: 6.14, height: 9.21, kdp: false, ingram: true },
  { label: '7 × 10"', width: 7, height: 10, kdp: true, ingram: true },
  { label: '8 × 10"', width: 8, height: 10, kdp: true, ingram: true },
  { label: '8.5 × 8.5"', width: 8.5, height: 8.5, kdp: true, ingram: true },
  { label: '8.5 × 11"', width: 8.5, height: 11, kdp: true, ingram: true },
]
